### ISSUE TITLE
When I add LUN name, the program exits unexpectedly and i can't view Ticket. 

### ISSUE THREAD

**Issue by edumaia** [kairoaraujo/STGAdm#3]
**Scope: Allocate volumes to the host "XXXXX01 (CXXXXXXXXXXXXXX)" on storage **"VNX 0139"****

$ /opt/STGAdm/stgadm.py

[ Storage Adm                           ]
[ Version 0.4.1 - (c) 2016 Kairo Araujo ]
[ http://github.com/kairoaraujo/STGAdm  ]
[ BSD License                           ]

Main Menu:
1. Add new volumes to existent host. (create change)
2. Execute changes created.

Please choose an option: 1

 [ REQUEST INFORMATIONS ]

Ticket/Change/Work Order: WOTESTE
Hostname Client: XXXXXXXXX
WWN Server Client: CXXXXXXXXXXXXX
Total Disk Required (GB): 100
Default LUN size (GB): 50

[Storage Selection]

Select the system storage used by client:
0 : EMC VMAX XXXX
1 : EMC VMAX XXXX
2 : EMC VMAX XXXX
3 : EMC VMAX XXXX
4 : EMC VMAX XXXX
5 : EMC VNX  XXXX
6 : EMC VNX  XXXX
7 : EMC VNX  XXXX
8 : EMC VNX  XXXX
9 : IBM DS8K XXXX
10 : IBM DS8K XXXX
11 : IBM DS8K GX11
12 : IBM DS8K GY61
System Storage: 5

Getting the hostname used on storage and Storage Group Name ...

Please wait...
Client informations:
Storage Group Name used by WWNHBA identified as hostname.
Hostname used on storage is host

Is it a CLUSTER provisioning? [y/n]: N
Please give the TAG/SID (Code to identify) the LUNs.
Use a name to identify the environment or client.
Examples: DEV or MIGRATION or FOOBAR

With this code the LUNs will be create as TAG/SID_LUN_SSL:
Example: DEV_LUN_1 or MIGRATION_LUN_7 or FOOBAR_LUN_45

LUN SID(TAG): FBC_HOSTNAME_LUN_50 ==> **When I add LUN name, the program exits unexpectedly.**

$

**I do not visualize the ticket in the list below**

[ Storage Adm                           ]
[                                       ]
[ Version 0.4.1 - (c) 2016 Kairo Araujo ]
[ http://github.com/kairoaraujo/STGAdm  ]
[ BSD License                           ]
[                                       ]

Main Menu:
1. Add new volumes to existent host. (create change)
2. Execute changes created.

Please choose an option: 2

[Change/Ticket/WO Execution]

Select the Change/Ticket/WO to execute:

0 : change_WOXXXXXXXXX_hostname_HBAINFO.py
1 : change_WOXXXXXXXXX_hostname_HBAINFO_07062016_103544.py
2 : change_woXXXXXXXXX_hostname_HBAINFO_08052016_160639.py

What's change/ticket id you want execute?:

**I would like to see a log information, is it possible?**

**Comment by kairoaraujo** [comment]
The core problem is on PyStorage library. It was fixed on PyStorage version https://pypi.python.org/pypi/PyStorage/0.5.1 . 
It can be fixed easly using this version instead 0.5.0 :+1: 
About the log information, it is in review https://review.gerrithub.io/#/c/296883/
The version 0.4.2 of STGAdm will be released soon.

**Comment by kairoaraujo** [comment]
release v0.4.2 requires PySorage 0.5.1 that fixes that bug.
